"""Actualizar modelo Lead con campos faltantes

Revision ID: 081dffb86acf
Revises: 371ea4852379
Create Date: 2025-06-08 03:01:36.474450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081dffb86acf'
down_revision = '371ea4852379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contact_made', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('contact_date')
        batch_op.drop_column('contact_made')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
