"""Anadir creditos de busqueda IA a LenderProfile

Revision ID: 3213adebe7b8
Revises: 343f1eb410d8
Create Date: 2025-06-08 14:27:32.699596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3213adebe7b8'
down_revision = '343f1eb410d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lender_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_search_credits', sa.Integer(), nullable=False, server_default='3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lender_profiles', schema=None) as batch_op:
        batch_op.drop_column('ai_search_credits')

    # ### end Alembic commands ###
