"""Anadir campos de suscripcion a LenderProfile

Revision ID: 343f1eb410d8
Revises: e9e31d794654
Create Date: 2025-06-08 13:39:06.682168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343f1eb410d8'
down_revision = 'e9e31d794654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('leads_lender_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lender_profiles', ['lender_id'], ['id'])

    with op.batch_alter_table('lender_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_credits', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='inactive'))
        batch_op.create_unique_constraint('uq_lender_profiles_stripe_subscription_id', ['stripe_subscription_id'])
        batch_op.create_unique_constraint('uq_lender_profiles_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lender_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lender_profiles_user_id', type_='unique')
        batch_op.drop_constraint('uq_lender_profiles_stripe_subscription_id', type_='unique')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('lead_credits')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('leads_lender_id_fkey', 'users', ['lender_id'], ['id'])

    # ### end Alembic commands ###
